version: '3.9'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - "dev-db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass


  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:rw
    command: sh -c "python manage.py wait_for_db && 
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_USER=dev_user
      - DB_PASSWORD=dev_pass
      - DB_NAME=dev_db
    depends_on:
      - db

volumes:
  dev-db-data:
